name: Mac OS

on: [push]

# 设置环境变量
env:
  # https://cmake.org/cmake/help/latest/envvar/CTEST_OUTPUT_ON_FAILURE.html
  CTEST_OUTPUT_ON_FAILURE: true

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      
      - name: configure
        run: |
          cmake -B build/debug -D CMAKE_BUILD_TYPE=Debug
          cmake -B build/release -D CMAKE_BUILD_TYPE=Release

      - name: build
        run: |
          cmake --build build/debug --config Debug
          cmake --build build/release --config Release
        
      - name: test
        run: |
          cd build/debug
          ctest --build-config Debug
          cd ../..
          cd build/release
          ctest --build-config Release
          cd ../..
