name: MacOS and Ubuntu

on: [push]

# 设置环境变量
env:
  # https://cmake.org/cmake/help/latest/envvar/CTEST_OUTPUT_ON_FAILURE.html
  CTEST_OUTPUT_ON_FAILURE: true
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    name: Buiod on os ${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      
      - name: configure
        run: |
          cmake -B ${{github.workspace}}/build -D CMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: build
        run: |
          cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
        
      - name: test
        working-directory: ${{github.workspace}}/build
        # Execute tests defined by the CMake configuration.
        # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
        run: |
          ctest --build-config ${{env.BUILD_TYPE}}
